-- subscription
<#list subscr as st>
INSERT INTO SUBSCRIPTION (ECHOAREA_ID , LINK_ID) VALUES (SELECT ID FROM ECHOAREA WHERE NAME = '${st.area}', SELECT ID FROM LINKS WHERE FTN_ADDRESS = '${st.node}');
</#list>